export const USER_TYPE_SUBSCRIBER = 'SUBSCRIBER';
export const USER_TYPE_GOFUNDIS = 'GOFUNDIS';
export const USER_TYPE_ALL = 'ALL';

export const TASK_STATYS_COMPLETED = 'COMPLETED';
export const TASK_STATYS_ASSIGNED = 'ASSIGNED';
export const TASK_STATYS_UNASSIGNED = 'UNASSIGNED';
export const TASK_STATYS_DECLINED = 'DECLINED';
export const TASK_STATYS_CANCELLED = 'CANCELLED';

export const CATEGORY_ALL = 'ALL CATEGORIES';
export const CATEGORY_NEW_INSTALL_DECODER = 'NEW INSTALLATION - DECODER';
export const CATEGORY_NEW_INSTALL_SIGNAL = 'NEW INSTALLATION - ANTENNA/SIGNAL';
export const CATEGORY_NEW_INSTALL_ERROR = 'NEW INSTALLATION - OTHER/ERROR';
export const CATEGORY_REPAIR_INSTALL_DECODER = 'REPAIR INSTALLATION - DECODER';
export const CATEGORY_REPAIR_INSTALL_SIGNAL = 'REPAIR INSTALLATION - ANTENNA/SIGNAL';

export const GOFUNDIS_STATYS_OFFLINE = 'OFFLINE';
export const GOFUNDIS_STATYS_ONLINE = 'ONLINE';
export const GOFUNDIS_ALL = 'ALL';

export const SUBSCRIBERS_ALL = 'subscriber';
